### ISSUE TITLE
Incomplete relation

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-ieee#6]
In `rfcsubseries`, relation’s bibitem specifies a complete citation:

https://github.com/ietf-ribose/relaton-data-rfcsubseries/blob/main/data/BCP0016.yaml#L23

In `ieee`, it’s just a formatted reference:

https://github.com/ietf-ribose/relaton-data-ieee/blob/main/data/IEEE_PC57-12-90_D-6.2021-06.yaml#L56

Can we expect a consistent shape of this property? Which one of the above would it be?

From what I can see, https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc#L445 specifies `bibitem` to be a `BibliographicItem` instance.

**Comment by ronaldtse** [comment]
@strogonoff a `BibliographicItem` supports a `formattedRef` which is the "display string" version of a bibliographic item. Both items as shown are valid.

In `rfcsubseries`, we made the decision to include the full RFC reference within a subseries items (e.g. BCP) because these items do not have content, and rely on its included references for content.

In `ieee`, we will not include the full references due to content size. It may also lead to content loops (doc A "updates" doc B which is "superseded" by doc A).

**Comment by strogonoff** [comment]
@ronaldtse does this mean literally all properties in `BibliographicItem` are optional? And if I expect a `BibliographicItem` instance, it can be an empty object with just a `formattedRef`?

**Comment by ronaldtse** [comment]
Yes. There are occasions when people provide a bibliographic reference, all we know is a string and nothing more…

**Comment by strogonoff** [comment]
That shouldn’t be a BibliographicItem, but BibliographicItemReference or something along those lines. Then, if you want, you can define relation to be a union of those types.

When all properties are optional, it dramatically reduces the usefulness of a spec. By that logic, BibXML service can state that it returns a BibliographicItem and just return a formatted ref (or empty object) to comply. If consumer gets a BibliographicItem, there are minimum expectations about it.

**Comment by ronaldtse** [comment]
> That shouldn’t be a BibliographicItem, but BibliographicItemReference or something along those lines. Then, if you want, you can define relation to be a union of those types.

Maybe. This could be a good distinction to make.
